name: Testing CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Ant
      run: ant -noinput -buildfile ./KF5012DarthMaulApplication/build.xml
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ./KF5012DarthMaulApplication/build/jar
    - name: Testing Report
      uses: mikepenz/action-junit-report@v2.4.1
      with:
          report_paths: './KF5012DarthMaulApplication/build/jar/TEST-*.xml'

      
